# 8.3-noble docker pull mongo:8.3-noble
services:
  mongodb:
    image: mongo:8.3-noble

    container_name: mongodb

    ports:
      - "27007:27017"

    volumes:
      - mongodata:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD} # هيروح يبص على ال .env ويأخد القيمة منه

    networks:
      - backend

    restart: always

  postgres:
    image: pgvector/pgvector:pg18
    container_name: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgresdata:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  mongodata:
  postgresdata:
